### ISSUE TITLE
Application scope of the interval newton method

### ISSUE THREAD

**Issue by The-Kite-Runner** [dpsanders/ValidatedNumerics.jl#161] opened 2016-07-12 02:11 UTC
Excuse me, I have tried some examples about interval equation calculation, and I'm confused by the following questions:

**application scope of the interval newton method**

A simple function is okay.

g(x) = x^2 - 2;
`tic();newton(g,(-5..5));toc()  # elapsed time: 3.824327481 seconds

however, function like the following seems unable to be solved

`f(x) = x^2 + (1..3)*x - (7..9)`

and can the method be used to solve a set of equations like this

$f1(x,y)=x^2 + y^2 - (2..6)=0$

$f2(x,y)=x^2 + (3..4) * y^2 - (1..1)=0$

**calculation speed**

When I try [Wilkinson-type polynomials](https://github.com/dpsanders/ValidatedNumerics.jl/blob/master/examples/Roots%20of%20Wilkinson%20polynomials.ipynb) with Ijulia, the calculation speed is terribly slow. (If I use Juno, even slower)

My PC(windows 8.1 64bit, 8G RAM, I5 CPU): **1.630687196** seconds (54897236 bytes allocated, 4.59% gc time)

The example : **4.451800** seconds (1.18 M allocations: 56.450 MB, 1.01% gc time)

Is it because: 

> WARNING: CRlibm not properly installed. Try running Pkg.build("CRlibm") to fix it. Falling back to use MPFR. Note that Windows is not yet supported.

**subscriptify error**

_MethodError: `subscriptify` has no method matching subscriptify(::Int32)_

 in representation at C:\Users\123\.julia\v0.4\ValidatedNumerics\src\display.jl:118
 in show at C:\Users\123\.julia\v0.4\ValidatedNumerics\src\display.jl:179
 in show_default at show.jl:33
 in showcompact_lim at show.jl:120
 in sprint at iostream.jl:206
 in alignment at show.jl:1014
 in print_matrix at show.jl:1089
 in print_matrix at show.jl:1081
 in anonymous at replutil.jl:23
 in with_output_limit at show.jl:1278
 in writemime at replutil.jl:23
 in writemime at multimedia.jl:43
 in sprint at iostream.jl:206
 in display_dict at C:\Users\123\.julia\v0.4\IJulia\src\execute_request.jl:26

Thanks.

**Comment by dpsanders** [comment] 2016-07-12 13:00
1. The interval Newton method is not designed for equations that themselves contain intervals. What should the definition of the solution set be in that case?

2. Using MPFR will definitely be much slower than using Float64. Tony Kelman had a talk last year and a workshop this year at JuliaCon about how to set up compiling binary dependencies for Windows. If you would like to do this for `CRlibm`, that would be excellent.

3. I don't understand the `subscriptify` error with the `Int32` argument. You can try changing the argument type in the definition of `subscriptify` to `Integer` and see if that helps. Please feel free to send a Pull Request if that works.

**Comment by dpsanders** [comment] 2016-07-12 13:00
By the way, in the future, it would be great if you could separate out unrelated questions into separate issues, thanks!

**Comment by dpsanders** [comment] 2016-07-12 13:02
Do you have a 32-bit version of Julia or something like that? I don't understand why `subscriptify` is getting called with an `Int32` argument.

**Comment by dpsanders** [comment] 2016-07-12 13:03
For solving systems of equations, you need a multi-dimensional version of the Newton or Krawczyk method. It is not too difficult to write a basic one -- see e.g. my talk at JuliaCon 2016. But we have not implemented a robust one yet.

**Comment by dpsanders** [comment] 2016-07-12 13:04
But again, that will not necessarily be expected to work for equations where intervals appear explicitly. Can I ask what the application area here is? I have not seen people try to solve such equations in the literature; do you have a reference?

**Comment by The-Kite-Runner** [comment] 2016-07-13 12:02
Thanks for your patient response. In fact, I'm a rookie of github and Julia with poor English, and I will try to express my ideas clearer.

I want to repeat an old paper and find a tool to do this task, since it's only part of my interest. The previously mentioned examples are show as below:


![image](https://cloud.githubusercontent.com/assets/18660347/16802679/84857548-4934-11e6-9198-68e3373ce5ff.png)

![image](https://cloud.githubusercontent.com/assets/18660347/16802688/8ecd1bf0-4934-11e6-8662-a12026ff22c1.png)

I will try to catch up with some other information you mentioned. Thanks again for your patience and kindness, 

[Wang_Alvarado_1992_Interval arithmetic in power flow analysis.pdf](https://github.com/dpsanders/ValidatedNumerics.jl/files/361413/Wang_Alvarado_1992_Interval.arithmetic.in.power.flow.analysis.pdf)

**Comment by dpsanders** [comment] 2016-07-13 12:19
Thanks for the reference. 
I'm not sure why the `newton` function is not working, since you can do it by hand:

```
f(x) = x^2 + (1..3)*x - (7..9)
x = 0..6

N(f, x) = ( m = Interval(mid(x)); m - f(m) / ForwardDiff.derivative(f, x) )

julia> x = 0..6
[0, 6]

julia> x = x ∩ N(f, x)
[0, 2.80001]

julia> x = x ∩ N(f, x)
[1.49767, 2.80001]

julia> x = x ∩ N(f, x)
[1.49767, 2.70791]

julia> x = x ∩ N(f, x)
[1.49767, 2.70791]
```

**Comment by dpsanders** [comment] 2016-07-13 12:32
The 2D system is similar:

```julia
f1(x, y) = x^2 + y^2 - (3..5)
 f2(x, y) = x^2 + (8..10)*y^2 - 9

 f(xx) = ( (x,y) = xx; [f1(x,y), f2(x,y)] )
 # ForwardDiff needs a function that takes a vector and returns a vector

 x0 = [ (0.5..3), (0.4..2) ]
 m = [Interval(mid(x)) for x in x0]   # midpoints as intervals

 J = ForwardDiff.jacobian(f, x0)
 julia> J \ f(m)
 2-element Array{ValidatedNumerics.Interval{Float64},1}:
  [-∞, ∞]
  [-∞, ∞]
```

Unfortunately, using Julia's built-in linear algebra, which does a generic LU, leads to being unable to successfully solve the system. The paper you cite suggests using Gauss--Seidel instead for solving the linear system `J.x = f(m)`, which has not yet been implemented.

**Comment by The-Kite-Runner** [comment] 2016-07-13 14:48
Ah!  Thanks for your  careful explaination. 

An expert like you  actually deduced step by step for a nearly complete unfamiliar rookie! Fantastic github.

I think I must consider this problem more carefully, and thanks again!

**Comment by dpsanders** [comment] 2016-07-13 16:53
I have been trying to do the 2-dimensional problem, but I don't understand what is happening at the bottom of the left-hand column of page 1347 of the article. They evaluate the Jacobian `J(xm, ym)` at the midpoint `(xm, ym)` of the interval (not their notation). However, as far as I understand, the interval Newton method rather requires to take the Jacobian over the *entire* interval, and this leads to an unsolvable system of equations which will require bisection.

**Comment by dpsanders** [comment] 2016-07-13 17:09
I'm wrong, they do use the correct Jacobian, over the whole interval. But in that case I don't see how they get the Gauss-Seidel method to work.

**Comment by The-Kite-Runner** [comment] 2016-07-13 23:29
Yes, they dedicated a significant portion discussing the importance of combination of  Newton and Gauss-Seidel method, and how to use newton is presented clearly, however, there are nearly no information  about how to use the Gauss-Seidel method except that :

> Page 1343：The most  widely  used  method  to  solve  interval  linear equations  is  Gauss-Seidel  iteration.  While  this  may  seem like  a bad  idea, the purpose of  Gauss-Seidel  iterations  here is  not to solve the power flow problem,  but to solve the linear  equations that result  from Newton’s  method, and to do so with  as little  conservatism  as possible.  In order  to converge to a solution, this method requires that the matrix be an  M-matrix. (_The referred article_ is RIS F N. Interval analysis and applications to linear algebra.[D]. University of Oxford, 1972.) 

I search on google scholar, and find out the Interval Gauss-Seidel method, I just wonder how to choose the initial value for each iteration.（ALEFELD G, MAYER G. Interval analysis: theory and applications[J]. Journal of Computational and Applied Mathematics, 2000, 121(1–2): 421–464.）

![image](https://cloud.githubusercontent.com/assets/18660347/16823062/c2d212ac-4993-11e6-81ef-a3b3d06a9fe7.png)

Thanks again.

[Alefeld_Mayer_2000_Interval analysis.pdf](https://github.com/dpsanders/ValidatedNumerics.jl/files/362713/Alefeld_Mayer_2000_Interval.analysis.pdf)

**Comment by dpsanders** [comment] 2016-07-25 12:02
I have spent a lot of effort on this, but without ever being able to reproduce the results from the Wang paper, even though my Gauss-Seidel routine seems to be working (checked with other examples). So I'm going to close this.

**Comment by dpsanders** [comment] 2016-07-25 12:02
Thanks for bringing it to my attention, though!

**Closed by dpsanders** 2016-07-25 12:02 UTC
